site_name: apidocs
docs_dir: out
theme:
  name: readthedocs
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
