# This file is generated by Vest!
# Do not modify!
# source: res://addons/vest/test/vest-test.gd
extends "res://addons/vest/_generated-mixins/5-3c4a4dd7.gd"

class_name VestTest

func __get_vest_mixins() -> Array:
	return []