extends Object
class_name NameProvider

static var _adjectives: PackedStringArray
static var _animals: PackedStringArray

static func _pick_random(from: PackedStringArray) -> String:
	return from[randi_range(0, from.size()-1)]

static func name():
	return ("%s %s" % [
		NameProvider._pick_random(NameProvider._adjectives),
		NameProvider._pick_random(NameProvider._animals)
	]).capitalize()

static func _static_init():
	# Source for adjectives: https://gist.github.com/hugsy/8910dc78d208e40de42deb29e62df913
	# Source for animals: https://gist.github.com/atduskgreg/3cf8ef48cb0d29cf151bedad81553a54

	_adjectives = PackedStringArray([
		"abandoned", "able", "absolute", "adorable", "adventurous", "academic", 
		"acceptable", "acclaimed", "accomplished", "accurate", "aching", "acidic", 
		"acrobatic", "active", "actual", "adept", "admirable", "admired", 
		"adolescent", "adorable", "adored", "advanced", "afraid", "affectionate", 
		"aged", "aggravating", "aggressive", "agile", "agitated", "agonizing", 
		"agreeable", "ajar", "alarmed", "alarming", "alert", "alienated", 
		"alive", "all", "altruistic", "amazing", "ambitious", "ample", 
		"amused", "amusing", "anchored", "ancient", "angelic", "angry", 
		"anguished", "animated", "annual", "another", "antique", "anxious", 
		"any", "apprehensive", "appropriate", "apt", "arctic", "arid", 
		"aromatic", "artistic", "ashamed", "assured", "astonishing", "athletic", 
		"attached", "attentive", "attractive", "austere", "authentic", "authorized", 
		"automatic", "avaricious", "average", "aware", "awesome", "awful", 
		"awkward", "babyish", "bad", "back", "baggy", "bare", 
		"barren", "basic", "beautiful", "belated", "beloved", "beneficial", 
		"better", "best", "bewitched", "big", "big-hearted", "biodegradable", 
		"bite-sized", "bitter", "black", "black-and-white", "bland", "blank", 
		"blaring", "bleak", "blind", "blissful", "blond", "blue", 
		"blushing", "bogus", "boiling", "bold", "bony", "boring", 
		"bossy", "both", "bouncy", "bountiful", "bowed", "brave", 
		"breakable", "brief", "bright", "brilliant", "brisk", "broken", 
		"bronze", "brown", "bruised", "bubbly", "bulky", "bumpy", 
		"buoyant", "burdensome", "burly", "bustling", "busy", "buttery", 
		"buzzing", "calculating", "calm", "candid", "canine", "capital", 
		"carefree", "careful", "careless", "caring", "cautious", "cavernous", 
		"celebrated", "charming", "cheap", "cheerful", "cheery", "chief", 
		"chilly", "chubby", "circular", "classic", "clean", "clear", 
		"clear-cut", "clever", "close", "closed", "cloudy", "clueless", 
		"clumsy", "cluttered", "coarse", "cold", "colorful", "colorless", 
		"colossal", "comfortable", "common", "compassionate", "competent", "complete", 
		"complex", "complicated", "composed", "concerned", "concrete", "confused", 
		"conscious", "considerate", "constant", "content", "conventional", "cooked", 
		"cool", "cooperative", "coordinated", "corny", "corrupt", "costly", 
		"courageous", "courteous", "crafty", "crazy", "creamy", "creative", 
		"creepy", "criminal", "crisp", "critical", "crooked", "crowded", 
		"cruel", "crushing", "cuddly", "cultivated", "cultured", "cumbersome", 
		"curly", "curvy", "cute", "cylindrical", "damaged", "damp", 
		"dangerous", "dapper", "daring", "darling", "dark", "dazzling", 
		"dead", "deadly", "deafening", "dear", "dearest", "decent", 
		"decimal", "decisive", "deep", "defenseless", "defensive", "defiant", 
		"deficient", "definite", "definitive", "delayed", "delectable", "delicious", 
		"delightful", "delirious", "demanding", "dense", "dental", "dependable", 
		"dependent", "descriptive", "deserted", "detailed", "determined", "devoted", 
		"different", "difficult", "digital", "diligent", "dim", "dimpled", 
		"dimwitted", "direct", "disastrous", "discrete", "disfigured", "disgusting", 
		"disloyal", "dismal", "distant", "downright", "dreary", "dirty", 
		"disguised", "dishonest", "dismal", "distant", "distinct", "distorted", 
		"dizzy", "dopey", "doting", "double", "downright", "drab", 
		"drafty", "dramatic", "dreary", "droopy", "dry", "dual", 
		"dull", "dutiful", "each", "eager", "earnest", "early", 
		"easy", "easy-going", "ecstatic", "edible", "educated", "elaborate", 
		"elastic", "elated", "elderly", "electric", "elegant", "elementary", 
		"elliptical", "embarrassed", "embellished", "eminent", "emotional", "empty", 
		"enchanted", "enchanting", "energetic", "enlightened", "enormous", "enraged", 
		"entire", "envious", "equal", "equatorial", "essential", "esteemed", 
		"ethical", "euphoric", "even", "evergreen", "everlasting", "every", 
		"evil", "exalted", "excellent", "exemplary", "exhausted", "excitable", 
		"excited", "exciting", "exotic", "expensive", "experienced", "expert", 
		"extraneous", "extroverted", "extra-large", "extra-small", "fabulous", "failing", 
		"faint", "fair", "faithful", "fake", "false", "familiar", 
		"famous", "fancy", "fantastic", "far", "faraway", "far-flung", 
		"far-off", "fast", "fat", "fatal", "fatherly", "favorable", 
		"favorite", "fearful", "fearless", "feisty", "feline", "female", 
		"feminine", "few", "fickle", "filthy", "fine", "finished", 
		"firm", "first", "firsthand", "fitting", "fixed", "flaky", 
		"flamboyant", "flashy", "flat", "flawed", "flawless", "flickering", 
		"flimsy", "flippant", "flowery", "fluffy", "fluid", "flustered", 
		"focused", "fond", "foolhardy", "foolish", "forceful", "forked", 
		"formal", "forsaken", "forthright", "fortunate", "fragrant", "frail", 
		"frank", "frayed", "free", "French", "fresh", "frequent", 
		"friendly", "frightened", "frightening", "frigid", "frilly", "frizzy", 
		"frivolous", "front", "frosty", "frozen", "frugal", "fruitful", 
		"full", "fumbling", "functional", "funny", "fussy", "fuzzy", 
		"gargantuan", "gaseous", "general", "generous", "gentle", "genuine", 
		"giant", "giddy", "gigantic", "gifted", "giving", "glamorous", 
		"glaring", "glass", "gleaming", "gleeful", "glistening", "glittering", 
		"gloomy", "glorious", "glossy", "glum", "golden", "good", 
		"good-natured", "gorgeous", "graceful", "gracious", "grand", "grandiose", 
		"granular", "grateful", "grave", "gray", "great", "greedy", 
		"green", "gregarious", "grim", "grimy", "gripping", "grizzled", 
		"gross", "grotesque", "grouchy", "grounded", "growing", "growling", 
		"grown", "grubby", "gruesome", "grumpy", "guilty", "gullible", 
		"gummy", "hairy", "half", "handmade", "handsome", "handy", 
		"happy", "happy-go-lucky", "hard", "hard-to-find", "harmful", "harmless", 
		"harmonious", "harsh", "hasty", "hateful", "haunting", "healthy", 
		"heartfelt", "hearty", "heavenly", "heavy", "hefty", "helpful", 
		"helpless", "hidden", "hideous", "high", "high-level", "hilarious", 
		"hoarse", "hollow", "homely", "honest", "honorable", "honored", 
		"hopeful", "horrible", "hospitable", "hot", "huge", "humble", 
		"humiliating", "humming", "humongous", "hungry", "hurtful", "husky", 
		"icky", "icy", "ideal", "idealistic", "identical", "idle", 
		"idiotic", "idolized", "ignorant", "ill", "illegal", "ill-fated", 
		"ill-informed", "illiterate", "illustrious", "imaginary", "imaginative", "immaculate", 
		"immaterial", "immediate", "immense", "impassioned", "impeccable", "impartial", 
		"imperfect", "imperturbable", "impish", "impolite", "important", "impossible", 
		"impractical", "impressionable", "impressive", "improbable", "impure", "inborn", 
		"incomparable", "incompatible", "incomplete", "inconsequential", "incredible", "indelible", 
		"inexperienced", "indolent", "infamous", "infantile", "infatuated", "inferior", 
		"infinite", "informal", "innocent", "insecure", "insidious", "insignificant", 
		"insistent", "instructive", "insubstantial", "intelligent", "intent", "intentional", 
		"interesting", "internal", "international", "intrepid", "ironclad", "irresponsible", 
		"irritating", "itchy", "jaded", "jagged", "jam-packed", "jaunty", 
		"jealous", "jittery", "joint", "jolly", "jovial", "joyful", 
		"joyous", "jubilant", "judicious", "juicy", "jumbo", "junior", 
		"jumpy", "juvenile", "kaleidoscopic", "keen", "key", "kind", 
		"kindhearted", "kindly", "klutzy", "knobby", "knotty", "knowledgeable", 
		"knowing", "known", "kooky", "kosher", "lame", "lanky", 
		"large", "last", "lasting", "late", "lavish", "lawful", 
		"lazy", "leading", "lean", "leafy", "left", "legal", 
		"legitimate", "light", "lighthearted", "likable", "likely", "limited", 
		"limp", "limping", "linear", "lined", "liquid", "little", 
		"live", "lively", "livid", "loathsome", "lone", "lonely", 
		"long", "long-term", "loose", "lopsided", "lost", "loud", 
		"lovable", "lovely", "loving", "low", "loyal", "lucky", 
		"lumbering", "luminous", "lumpy", "lustrous", "luxurious", "mad", 
		"made-up", "magnificent", "majestic", "major", "male", "mammoth", 
		"married", "marvelous", "masculine", "massive", "mature", "meager", 
		"mealy", "mean", "measly", "meaty", "medical", "mediocre", 
		"medium", "meek", "mellow", "melodic", "memorable", "menacing", 
		"merry", "messy", "metallic", "mild", "milky", "mindless", 
		"miniature", "minor", "minty", "miserable", "miserly", "misguided", 
		"misty", "mixed", "modern", "modest", "moist", "monstrous", 
		"monthly", "monumental", "moral", "mortified", "motherly", "motionless", 
		"mountainous", "muddy", "muffled", "multicolored", "mundane", "murky", 
		"mushy", "musty", "muted", "mysterious", "naive", "narrow", 
		"nasty", "natural", "naughty", "nautical", "near", "neat", 
		"necessary", "needy", "negative", "neglected", "negligible", "neighboring", 
		"nervous", "new", "next", "nice", "nifty", "nimble", 
		"nippy", "nocturnal", "noisy", "nonstop", "normal", "notable", 
		"noted", "noteworthy", "novel", "noxious", "numb", "nutritious", 
		"nutty", "obedient", "obese", "oblong", "oily", "oblong", 
		"obvious", "occasional", "odd", "oddball", "offbeat", "offensive", 
		"official", "old", "old-fashioned", "only", "open", "optimal", 
		"optimistic", "opulent", "orange", "orderly", "organic", "ornate", 
		"ornery", "ordinary", "original", "other", "our", "outlying", 
		"outgoing", "outlandish", "outrageous", "outstanding", "oval", "overcooked", 
		"overdue", "overjoyed", "overlooked", "palatable", "pale", "paltry", 
		"parallel", "parched", "partial", "passionate", "past", "pastel", 
		"peaceful", "peppery", "perfect", "perfumed", "periodic", "perky", 
		"personal", "pertinent", "pesky", "pessimistic", "petty", "phony", 
		"physical", "piercing", "pink", "pitiful", "plain", "plaintive", 
		"plastic", "playful", "pleasant", "pleased", "pleasing", "plump", 
		"plush", "polished", "polite", "political", "pointed", "pointless", 
		"poised", "poor", "popular", "portly", "posh", "positive", 
		"possible", "potable", "powerful", "powerless", "practical", "precious", 
		"present", "prestigious", "pretty", "precious", "previous", "pricey", 
		"prickly", "primary", "prime", "pristine", "private", "prize", 
		"probable", "productive", "profitable", "profuse", "proper", "proud", 
		"prudent", "punctual", "pungent", "puny", "pure", "purple", 
		"pushy", "putrid", "puzzled", "puzzling", "quaint", "qualified", 
		"quarrelsome", "quarterly", "queasy", "querulous", "questionable", "quick", 
		"quick-witted", "quiet", "quintessential", "quirky", "quixotic", "quizzical", 
		"radiant", "ragged", "rapid", "rare", "rash", "raw", 
		"recent", "reckless", "rectangular", "ready", "real", "realistic", 
		"reasonable", "red", "reflecting", "regal", "regular", "reliable", 
		"relieved", "remarkable", "remorseful", "remote", "repentant", "required", 
		"respectful", "responsible", "repulsive", "revolving", "rewarding", "rich", 
		"rigid", "right", "ringed", "ripe", "roasted", "robust", 
		"rosy", "rotating", "rotten", "rough", "round", "rowdy", 
		"royal", "rubbery", "rundown", "ruddy", "rude", "runny", 
		"rural", "rusty", "sad", "safe", "salty", "same", 
		"sandy", "sane", "sarcastic", "sardonic", "satisfied", "scaly", 
		"scarce", "scared", "scary", "scented", "scholarly", "scientific", 
		"scornful", "scratchy", "scrawny", "second", "secondary", "second-hand", 
		"secret", "self-assured", "self-reliant", "selfish", "sentimental", "separate", 
		"serene", "serious", "serpentine", "several", "severe", "shabby", 
		"shadowy", "shady", "shallow", "shameful", "shameless", "sharp", 
		"shimmering", "shiny", "shocked", "shocking", "shoddy", "short", 
		"short-term", "showy", "shrill", "shy", "sick", "silent", 
		"silky", "silly", "silver", "similar", "simple", "simplistic", 
		"sinful", "single", "sizzling", "skeletal", "skinny", "sleepy", 
		"slight", "slim", "slimy", "slippery", "slow", "slushy", 
		"small", "smart", "smoggy", "smooth", "smug", "snappy", 
		"snarling", "sneaky", "sniveling", "snoopy", "sociable", "soft", 
		"soggy", "solid", "somber", "some", "spherical", "sophisticated", 
		"sore", "sorrowful", "soulful", "soupy", "sour", "Spanish", 
		"sparkling", "sparse", "specific", "spectacular", "speedy", "spicy", 
		"spiffy", "spirited", "spiteful", "splendid", "spotless", "spotted", 
		"spry", "square", "squeaky", "squiggly", "stable", "staid", 
		"stained", "stale", "standard", "starchy", "stark", "starry", 
		"steep", "sticky", "stiff", "stimulating", "stingy", "stormy", 
		"straight", "strange", "steel", "strict", "strident", "striking", 
		"striped", "strong", "studious", "stunning", "stupendous", "stupid", 
		"sturdy", "stylish", "subdued", "submissive", "substantial", "subtle", 
		"suburban", "sudden", "sugary", "sunny", "super", "superb", 
		"superficial", "superior", "supportive", "sure-footed", "surprised", "suspicious", 
		"svelte", "sweaty", "sweet", "sweltering", "swift", "sympathetic", 
		"tall", "talkative", "tame", "tan", "tangible", "tart", 
		"tasty", "tattered", "taut", "tedious", "teeming", "tempting", 
		"tender", "tense", "tepid", "terrible", "terrific", "testy", 
		"thankful", "that", "these", "thick", "thin", "third", 
		"thirsty", "this", "thorough", "thorny", "those", "thoughtful", 
		"threadbare", "thrifty", "thunderous", "tidy", "tight", "timely", 
		"tinted", "tiny", "tired", "torn", "total", "tough", 
		"traumatic", "treasured", "tremendous", "tragic", "trained", "tremendous", 
		"triangular", "tricky", "trifling", "trim", "trivial", "troubled", 
		"true", "trusting", "trustworthy", "trusty", "truthful", "tubby", 
		"turbulent", "twin", "ugly", "ultimate", "unacceptable", "unaware", 
		"uncomfortable", "uncommon", "unconscious", "understated", "unequaled", "uneven", 
		"unfinished", "unfit", "unfolded", "unfortunate", "unhappy", "unhealthy", 
		"uniform", "unimportant", "unique", "united", "unkempt", "unknown", 
		"unlawful", "unlined", "unlucky", "unnatural", "unpleasant", "unrealistic", 
		"unripe", "unruly", "unselfish", "unsightly", "unsteady", "unsung", 
		"untidy", "untimely", "untried", "untrue", "unused", "unusual", 
		"unwelcome", "unwieldy", "unwilling", "unwitting", "unwritten", "upbeat", 
		"upright", "upset", "urban", "usable", "used", "useful", 
		"useless", "utilized", "utter", "vacant", "vague", "vain", 
		"valid", "valuable", "vapid", "variable", "vast", "velvety", 
		"venerated", "vengeful", "verifiable", "vibrant", "vicious", "victorious", 
		"vigilant", "vigorous", "villainous", "violet", "violent", "virtual", 
		"virtuous", "visible", "vital", "vivacious", "vivid", "voluminous", 
		"wan", "warlike", "warm", "warmhearted", "warped", "wary", 
		"wasteful", "watchful", "waterlogged", "watery", "wavy", "wealthy", 
		"weak", "weary", "webbed", "wee", "weekly", "weepy", 
		"weighty", "weird", "welcome", "well-documented", "well-groomed", "well-informed", 
		"well-lit", "well-made", "well-off", "well-to-do", "well-worn", "wet", 
		"which", "whimsical", "whirlwind", "whispered", "white", "whole", 
		"whopping", "wicked", "wide", "wide-eyed", "wiggly", "wild", 
		"willing", "wilted", "winding", "windy", "winged", "wiry", 
		"wise", "witty", "wobbly", "woeful", "wonderful", "wooden", 
		"woozy", "wordy", "worldly", "worn", "worried", "worrisome", 
		"worse", "worst", "worthless", "worthwhile", "worthy", "wrathful", 
		"wretched", "writhing", "wrong", "wry", "yawning", "yearly", 
		"yellow", "yellowish", "young", "youthful", "yummy", "zany", 
		"zealous", "zesty", "zigzag", 
	])
	
	_animals = PackedStringArray([
		"canidae", "felidae", "cat", "cattle", "dog", "donkey", 
		"goat", "guinea pig", "horse", "pig", "rabbit", "fancy rat varieties", 
		"laboratory rat strains", "sheep breeds", "water buffalo breeds", "chicken breeds", "duck breeds", "goose breeds", 
		"pigeon breeds", "turkey breeds", "aardvark", "aardwolf", "african buffalo", "african elephant", 
		"african leopard", "albatross", "alligator", "alpaca", "american buffalo (bison)", "american robin", 
		"amphibian", "list", "anaconda", "angelfish", "anglerfish", "ant", 
		"anteater", "antelope", "antlion", "ape", "aphid", "arabian leopard", 
		"arctic fox", "arctic wolf", "armadillo", "arrow crab", "asp", "ass (donkey)", 
		"baboon", "badger", "bald eagle", "bandicoot", "barnacle", "barracuda", 
		"basilisk", "bass", "bat", "beaked whale", "bear", "list", 
		"beaver", "bedbug", "bee", "beetle", "bird", "list", 
		"bison", "blackbird", "black panther", "black widow spider", "blue bird", "blue jay", 
		"blue whale", "boa", "boar", "bobcat", "bobolink", "bonobo", 
		"booby", "box jellyfish", "bovid", "buffalo, african", "buffalo, american (bison)", "bug", 
		"butterfly", "buzzard", "camel", "canid", "cape buffalo", "capybara", 
		"cardinal", "caribou", "carp", "cat", "list", "catshark", 
		"caterpillar", "catfish", "cattle", "list", "centipede", "cephalopod", 
		"chameleon", "cheetah", "chickadee", "chicken", "list", "chimpanzee", 
		"chinchilla", "chipmunk", "clam", "clownfish", "cobra", "cockroach", 
		"cod", "condor", "constrictor", "coral", "cougar", "cow", 
		"coyote", "crab", "crane", "crane fly", "crawdad", "crayfish", 
		"cricket", "crocodile", "crow", "cuckoo", "cicada", "damselfly", 
		"deer", "dingo", "dinosaur", "list", "dog", "list", 
		"dolphin", "donkey", "list", "dormouse", "dove", "dragonfly", 
		"dragon", "duck", "list", "dung beetle", "eagle", "earthworm", 
		"earwig", "echidna", "eel", "egret", "elephant", "elephant seal", 
		"elk", "emu", "english pointer", "ermine", "falcon", "ferret", 
		"finch", "firefly", "fish", "flamingo", "flea", "fly", 
		"flyingfish", "fowl", "fox", "frog", "fruit bat", "gamefowl", 
		"list", "galliform", "list", "gazelle", "gecko", "gerbil", 
		"giant panda", "giant squid", "gibbon", "gila monster", "giraffe", "goat", 
		"list", "goldfish", "goose", "list", "gopher", "gorilla", 
		"grasshopper", "great blue heron", "great white shark", "grizzly bear", "ground shark", "ground sloth", 
		"grouse", "guan", "list", "guanaco", "guineafowl", "list", 
		"guinea pig", "list", "gull", "guppy", "haddock", "halibut", 
		"hammerhead shark", "hamster", "hare", "harrier", "hawk", "hedgehog", 
		"hermit crab", "heron", "herring", "hippopotamus", "hookworm", "hornet", 
		"horse", "list", "hoverfly", "hummingbird", "humpback whale", "hyena", 
		"iguana", "impala", "irukandji jellyfish", "jackal", "jaguar", "jay", 
		"jellyfish", "junglefowl", "kangaroo", "kangaroo mouse", "kangaroo rat", "kingfisher", 
		"kite", "kiwi", "koala", "koi", "komodo dragon", "krill", 
		"ladybug", "lamprey", "landfowl", "land snail", "lark", "leech", 
		"lemming", "lemur", "leopard", "leopon", "limpet", "lion", 
		"lizard", "llama", "lobster", "locust", "loon", "louse", 
		"lungfish", "lynx", "macaw", "mackerel", "magpie", "mammal", 
		"manatee", "mandrill", "manta ray", "marlin", "marmoset", "marmot", 
		"marsupial", "marten", "mastodon", "meadowlark", "meerkat", "mink", 
		"minnow", "mite", "mockingbird", "mole", "mollusk", "mongoose", 
		"monitor lizard", "monkey", "moose", "mosquito", "moth", "mountain goat", 
		"mouse", "mule", "muskox", "narwhal", "newt", "new world quail", 
		"nightingale", "ocelot", "octopus", "old world quail", "opossum", "orangutan", 
		"orca", "ostrich", "otter", "owl", "ox", "panda", 
		"panther", "panthera hybrid", "parakeet", "parrot", "parrotfish", "partridge", 
		"peacock", "peafowl", "pelican", "penguin", "perch", "peregrine falcon", 
		"pheasant", "pig", "pigeon", "list", "pike", "pilot whale", 
		"pinniped", "piranha", "planarian", "platypus", "polar bear", "pony", 
		"porcupine", "porpoise", "portuguese man o' war", "possum", "prairie dog", "prawn", 
		"praying mantis", "primate", "ptarmigan", "puffin", "puma", "python", 
		"quail", "quelea", "quokka", "rabbit", "list", "raccoon", 
		"rainbow trout", "rat", "rattlesnake", "raven", "ray (batoidea)", "ray (rajiformes)", 
		"red panda", "reindeer", "reptile", "rhinoceros", "right whale", "roadrunner", 
		"rodent", "rook", "rooster", "roundworm", "saber-toothed cat", "sailfish", 
		"salamander", "salmon", "sawfish", "scale insect", "scallop", "scorpion", 
		"seahorse", "sea lion", "sea slug", "sea snail", "shark", "list", 
		"sheep", "list", "shrew", "shrimp", "silkworm", "silverfish", 
		"skink", "skunk", "sloth", "slug", "smelt", "snail", 
		"snake", "list", "snipe", "snow leopard", "sockeye salmon", "sole", 
		"sparrow", "sperm whale", "spider", "spider monkey", "spoonbill", "squid", 
		"squirrel", "starfish", "star-nosed mole", "steelhead trout", "stingray", "stoat", 
		"stork", "sturgeon", "sugar glider", "swallow", "swan", "swift", 
		"swordfish", "swordtail", "tahr", "takin", "tapir", "tarantula", 
		"tarsier", "tasmanian devil", "termite", "tern", "thrush", "tick", 
		"tiger", "tiger shark", "tiglon", "toad", "tortoise", "toucan", 
		"trapdoor spider", "tree frog", "trout", "tuna", "turkey", "list", 
		"turtle", "tyrannosaurus", "urial", "vampire bat", "vampire squid", "vicuna", 
		"viper", "vole", "vulture", "wallaby", "walrus", "wasp", 
		"warbler", "water boa", "water buffalo", "weasel", "whale", "whippet", 
		"whitefish", "whooping crane", "wildcat", "wildebeest", "wildfowl", "wolf", 
		"wolverine", "wombat", "woodpecker", "worm", "wren", "xerinae", 
		"x-ray fish", "yak", "yellow perch", "zebra", "zebra finch", "animals by number of neurons", 
		"animals by size", "common household pests", "common names of poisonous animals", "alpaca", "bali cattle", "cat", 
		"cattle", "chicken", "dog", "domestic bactrian camel", "domestic canary", "domestic dromedary camel", 
		"domestic duck", "domestic goat", "domestic goose", "domestic guineafowl", "domestic hedgehog", "domestic pig", 
		"domestic pigeon", "domestic rabbit", "domestic silkmoth", "domestic silver fox", "domestic turkey", "donkey", 
		"fancy mouse", "fancy rat", "lab rat", "ferret", "gayal", "goldfish", 
		"guinea pig", "guppy", "horse", "koi", "llama", "ringneck dove", 
		"sheep", "siamese fighting fish", "society finch", "yak", "water buffalo"
	])
