name: Release

permissions:
  contents: write
  discussions: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.1.1
          use-dotnet: false
          include-templates: true
      - name: Verify setup
        run: godot --version
      - name: Build
        run: sh/build.sh
      - name: Parse version
        id: version
        run: |
          sh/version.sh envvar >> "$GITHUB_OUTPUT"
          sh/version.sh
      - name: Delete draft release(s)
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.VERSION }}
          files: build/*
          draft: true
          prerelease: true
